---
name: Build and Deploy

on:
  push:
    branches:
      - writing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install -g gitbook-cli gitbook-summary
          book sm -t "CallePuzzle Page" -i presentacion-proyecto
          gitbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: _book/
